#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/_lib.sh"
HUB="$(cd "$(dirname "$0")/.." && pwd)"
command -v hermes >/dev/null || exit 0

# Mount briefing skills as one category; Hermes's bundled/own skills untouched
mkdir -p "$HOME/.hermes/skills"
link "$HUB/skills" "$HOME/.hermes/skills/briefing"

# Capture tier-1 memory into git (adopt existing content on first run)
mkdir -p "$HOME/.hermes/memories"
for f in MEMORY.md USER.md; do
  src="$HOME/.hermes/memories/$f"; dst="$HUB/memory/hermes/$f"
  [ -f "$src" ] && [ ! -L "$src" ] && [ ! -s "$dst" ] && cp "$src" "$dst"
  touch "$dst"; link "$dst" "$src"
done

# Global directions: SOUL.md is the only file Hermes always injects globally.
# Keep whatever is above the marker (identity), regenerate the rest from directions/.
SOUL="$HOME/.hermes/SOUL.md"
MARK='<!-- briefing directions below - generated by adapters/hermes.sh, edit directions/AGENTS.md in your briefing repo -->'
touch "$SOUL"
tmp="$(mktemp)"
awk -v m="$MARK" '$0==m{exit} {print}' "$SOUL" > "$tmp"
printf '\n%s\n\n' "$MARK" >> "$tmp"
cat "$HUB/directions/AGENTS.md" >> "$tmp"
mv "$tmp" "$SOUL"

# Gate agent writes so nothing lands in the repo without your approval.
# Note: this changes your Hermes config. Remove these lines if you prefer
# unsupervised writes.
hermes config set memory.write_approval true
hermes config set skills.write_approval true
echo "hermes: ok (memory/skills write approval enabled)"
