#!/usr/bin/env bash
# ------------------------------------------------
# hermes.sh - wire Hermes to the hub: skills mount, memory capture,
# and a generated directions section inside SOUL.md
# ------------------------------------------------
set -euo pipefail
HUB="$(cd "$(dirname "$0")/.." && pwd)"
source "$HUB/lib/log.sh"
source "$HUB/lib/common.sh"
command -v hermes >/dev/null || exit 0

# Mount briefing skills as one category; Hermes's bundled/own skills untouched
run mkdir -p "$HOME/.hermes/skills"
link "$HUB/skills" "$HOME/.hermes/skills/briefing"

# Capture tier-1 memory into git (adopt existing content on first run)
run mkdir -p "$HOME/.hermes/memories"
for f in MEMORY.md USER.md; do
  src="$HOME/.hermes/memories/$f"; dst="$HUB/memory/hermes/$f"
  if [[ -f "$src" && ! -L "$src" && ! -s "$dst" ]]; then
    run cp "$src" "$dst"
  fi
  run touch "$dst"
  link "$dst" "$src"
done

# Global directions: SOUL.md is the only file Hermes always injects globally.
# Keep whatever is above the marker (identity), regenerate the rest from
# directions/. Matched by substring so older marker wordings migrate cleanly.
SOUL="$HOME/.hermes/SOUL.md"
MARK='<!-- briefing directions below - generated by adapters/hermes.sh, edit directions/AGENTS.md in your briefing repo -->'
tmp="$(mktemp)"
if [[ -f "$SOUL" ]]; then
  # keep everything above the marker, trimming trailing blank lines so
  # repeated runs stay byte-identical
  awk 'index($0, "briefing directions below"){exit} {lines[NR]=$0; n=NR}
       END{while(n>0 && lines[n]=="") n--; for(i=1;i<=n;i++) print lines[i]}' \
    "$SOUL" > "$tmp"
fi
printf '\n%s\n\n' "$MARK" >> "$tmp"
cat "$HUB/directions/AGENTS.md" >> "$tmp"
if [[ "${DRY_RUN:-0}" == "1" ]]; then
  printf 'would regenerate: %s (directions section)\n' "$SOUL"
  rm "$tmp"
else
  mv "$tmp" "$SOUL"
fi

# Gate agent writes so nothing lands in the repo without your approval.
# Note: this changes your Hermes config. Remove these lines if you prefer
# unsupervised writes.
run hermes config set memory.write_approval true
run hermes config set skills.write_approval true
info "hermes: ok (memory/skills write approval enabled)"
