# briefing unlink - detach a project from the hub (inverse of link)

cmd_unlink_help() {
  cat <<'EOF'
briefing unlink - detach a project directory from the briefing repo

Usage:
  briefing [-n|--dry-run] unlink <project-dir>

The inverse of `briefing link` (idempotent):
  1. removes skill links owned by this hub from .vibe/skills/,
     .cursor/skills/, and .claude/skills/ (links to other hubs and real
     files are left alone)
  2. removes the generated .cursor/rules/briefing.mdc (only when its
     briefing-hub stamp names this hub)
  3. removes the HERMES.md and CLAUDE.md -> AGENTS.md mirrors
  4. deregisters the project, so installs stop re-linking it

The project's own committed files (AGENTS.md, .briefing-skills) are never
touched. Empty directories left behind are pruned.
EOF
}

# prune_dir DIR - remove DIR only when it exists and is empty
prune_dir() {
  if [[ -d "$1" && -z "$(ls -A "$1")" ]]; then
    run rmdir "$1"
  fi
}

cmd_unlink() {
  local PROJECT TARGET l mdc mdc_hub
  PROJECT="${1:?usage: briefing unlink <project-dir>}"
  [[ "$PROJECT" == /* ]] || PROJECT="$PWD/$PROJECT"

  # A gone directory can still be deregistered; everything else needs it.
  if [[ -d "$PROJECT" ]]; then
    PROJECT="$(cd "$PROJECT" && pwd)"

    # 1. Skills: drop only links that point into this hub
    for TARGET in "$PROJECT/.vibe/skills" "$PROJECT/.cursor/skills" "$PROJECT/.claude/skills"; do
      if [[ -d "$TARGET" ]]; then
        for l in "$TARGET"/*; do
          [[ -L "$l" ]] || continue
          case "$(readlink "$l")" in "$HUB/skills/"*) run rm "$l" ;; esac
        done
        prune_dir "$TARGET"
      fi
    done
    prune_dir "$PROJECT/.vibe"
    prune_dir "$PROJECT/.claude"

    # 2. Cursor rule: only remove what this hub generated
    mdc="$PROJECT/.cursor/rules/briefing.mdc"
    if [[ -f "$mdc" ]]; then
      mdc_hub="$(sed -n 's/^briefing-hub: //p' "$mdc" 2>/dev/null | head -1)"
      if [[ "$mdc_hub" == "$HUB" ]]; then
        run rm "$mdc"
      else
        skip "left briefing.mdc (generated by another hub: ${mdc_hub:-unknown})"
      fi
    fi
    prune_dir "$PROJECT/.cursor/rules"
    prune_dir "$PROJECT/.cursor"

    # 3. Hermes and Claude mirrors (only when they are our symlinks)
    for l in HERMES.md CLAUDE.md; do
      if [[ "$(readlink "$PROJECT/$l" 2>/dev/null)" == "$PROJECT/AGENTS.md" ]]; then
        run rm "$PROJECT/$l"
      fi
    done
  fi

  # 4. Deregister
  if grep -qxF "$PROJECT" "$REG" 2>/dev/null; then
    if [[ "$DRY_RUN" == "1" ]]; then
      printf 'would deregister: %s from %s\n' "$PROJECT" "$REG"
    else
      grep -vxF "$PROJECT" "$REG" > "$REG.tmp" || true
      mv "$REG.tmp" "$REG"
    fi
  fi

  info "unlinked: $PROJECT"
}
