# briefing status - health check for wiring, projects, and the repo

cmd_status_help() {
  cat <<'EOF'
briefing status - health check

Usage:
  briefing status

Checks, without changing anything:
  - global wiring per installed agent (symlinks, generated sections)
  - every registered project (generated rule freshness, mirrors, skills)
  - the repo itself (uncommitted files, unpushed commits)

Exit code 0 when everything is healthy, 1 when something needs attention.
Repairs are one command away: `briefing install` (wiring) or
`briefing sync` (repo).
EOF
}

cmd_status() {
  cd "$HUB"

  echo "global"
  [[ "$(readlink "$HOME/.local/bin/briefing" 2>/dev/null)" == "$HUB/bin/briefing" ]] \
    && ok "briefing on PATH (~/.local/bin/briefing)" || bad "briefing not on PATH (run bin/briefing install)"

  # Vibe: symlinks can't go stale, just verify they point at the hub
  if command -v vibe >/dev/null; then
    [[ "$(readlink "$HOME/.vibe/AGENTS.md" 2>/dev/null)" == "$DIRECTIONS" ]] \
      && ok "vibe: ~/.vibe/AGENTS.md -> directions" || bad "vibe: ~/.vibe/AGENTS.md not linked"
    [[ "$(readlink "$HOME/.vibe/skills" 2>/dev/null)" == "$HUB/skills" ]] \
      && ok "vibe: ~/.vibe/skills -> skills" || bad "vibe: ~/.vibe/skills not linked"
  else skip "vibe: not installed"; fi

  # Hermes: SOUL.md carries a generated copy, compare it against the source
  if command -v hermes >/dev/null; then
    if awk 'f{print} index($0, "briefing directions below"){f=1}' "$HOME/.hermes/SOUL.md" 2>/dev/null \
         | sed '1{/^$/d}' | diff -q - "$DIRECTIONS" >/dev/null 2>&1; then
      ok "hermes: SOUL.md directions section current"
    else
      stale "hermes: SOUL.md directions section (run briefing install)"
    fi
    [[ "$(readlink "$HOME/.hermes/skills/briefing" 2>/dev/null)" == "$HUB/skills" ]] \
      && ok "hermes: skills mounted" || bad "hermes: skills not mounted"
    local f
    for f in MEMORY.md USER.md; do
      [[ "$(readlink "$HOME/.hermes/memories/$f" 2>/dev/null)" == "$HUB/memory/hermes/$f" ]] \
        && ok "hermes: $f captured" || bad "hermes: $f not captured"
    done
  else skip "hermes: not installed"; fi

  echo
  echo "projects"
  if [[ -s "$REG" ]]; then
    local p s t miss wrong other mdc mdc_hub mdc_ver cur_ver
    cur_ver="$(hub_version)"
    while IFS= read -r p; do
      echo "  $(basename "$p")"
      if [[ ! -d "$p" ]]; then bad "  directory gone ($p)"; continue; fi
      # Cursor rule: generated copy. The frontmatter carries provenance
      # (briefing-hub, briefing-version); the body must match directions
      # verbatim. Distinguish the reasons for divergence instead of a
      # catch-all "stale".
      mdc="$p/.cursor/rules/briefing.mdc"
      mdc_hub="$(sed -n 's/^briefing-hub: //p' "$mdc" 2>/dev/null | head -1)"
      mdc_ver="$(sed -n 's/^briefing-version: //p' "$mdc" 2>/dev/null | head -1)"
      if [[ ! -f "$mdc" ]]; then
        bad "  briefing.mdc missing (run briefing link $p)"
      elif [[ -n "$mdc_hub" && "$mdc_hub" != "$HUB" ]]; then
        stale "  briefing.mdc generated by another hub: $mdc_hub (run briefing link $p to regenerate from this one)"
      elif awk 'body{print;next} /^---$/ && ++n==2 {body=1}' "$mdc" \
             | diff -q - "$DIRECTIONS" >/dev/null 2>&1; then
        ok "  briefing.mdc current"
      elif [[ -n "$mdc_ver" && "$mdc_ver" != "$cur_ver" ]]; then
        stale "  briefing.mdc outdated: generated at $mdc_ver, hub is at $cur_ver (run briefing link $p)"
      else
        stale "  briefing.mdc differs from directions/AGENTS.md (run briefing link $p)"
      fi
      if [[ -f "$p/AGENTS.md" ]]; then
        [[ "$(readlink "$p/HERMES.md" 2>/dev/null)" == "$p/AGENTS.md" ]] \
          && ok "  HERMES.md mirror" || bad "  HERMES.md mirror missing"
      else
        skip "  no AGENTS.md (no HERMES.md mirror)"
      fi
      if [[ -f "$p/.briefing-skills" ]]; then
        while IFS= read -r s; do
          [[ -z "$s" || "${s:0:1}" == "#" ]] && continue
          if [[ ! -d "$HUB/skills/$s" ]]; then
            bad "  skill $s not in this hub's skills/ (edit $p/.briefing-skills or add the skill)"
            continue
          fi
          # A link that exists but points at a different hub is not
          # "missing"; report it as what it is.
          miss="" wrong="" other=""
          for t in .vibe/skills .cursor/skills; do
            if [[ "$(readlink "$p/$t/$s" 2>/dev/null)" == "$HUB/skills/$s" ]]; then
              continue
            elif [[ -L "$p/$t/$s" ]]; then
              wrong="$wrong $t"; other="$(readlink "$p/$t/$s")"
            else
              miss="$miss $t"
            fi
          done
          if [[ -z "$miss$wrong" ]]; then
            ok "  skill $s"
          else
            [[ -n "$wrong" ]] && stale "  skill $s linked to another hub in:$wrong (-> $other; run briefing link $p)"
            [[ -n "$miss" ]] && bad "  skill $s not linked in:$miss (run briefing link $p)"
          fi
        done < "$p/.briefing-skills"
      fi
    done < "$REG"
  else
    skip "no projects registered (run briefing link <dir>)"
  fi

  echo
  echo "repo"
  local dirty ahead
  dirty="$(git status --porcelain | wc -l)"
  if [[ "$dirty" -eq 0 ]]; then
    ok "working tree clean"
  else
    stale "$dirty uncommitted file(s), review and run briefing sync"
    git status --porcelain | sed 's/^/        /'
  fi
  ahead="$(git rev-list --count @{upstream}..HEAD 2>/dev/null || echo '?')"
  [[ "$ahead" == "0" ]] && ok "in sync with origin" || stale "$ahead commit(s) not pushed"

  exit "$FAIL"
}
