# ------------------------------------------------
# common.sh - shared helpers for briefing commands and adapters
#
# Environment:
#   DRY_RUN = 0 | 1   (1: print mutating actions instead of performing them)
# ------------------------------------------------

# run CMD... - execute a mutating command, or print it when DRY_RUN=1.
# Wrap every state-changing call in run so dry runs stay faithful.
run() {
  if [[ "${DRY_RUN:-0}" == "1" ]]; then
    printf 'would run: %s\n' "$*"
  else
    "$@"
  fi
}

# link SRC DST - safe symlink that never destroys a real file or directory:
# an existing non-symlink DST is preserved as DST.pre-briefing.bak first.
link() {
  if [[ -e "$2" && ! -L "$2" ]]; then
    run mv "$2" "$2.pre-briefing.bak"
  fi
  run ln -sfn "$1" "$2"
}

# unwire DST SRC - inverse of link: remove DST when it is the symlink to SRC
# that link() created, then restore the .pre-briefing.bak backup that link()
# may have preserved. A DST that is not our symlink is never touched (unless
# it is absent and a backup is waiting to come back).
unwire() {
  if [[ "$(readlink "$1" 2>/dev/null)" == "$2" ]]; then
    run rm "$1"
    if [[ -e "$1.pre-briefing.bak" ]]; then
      run mv "$1.pre-briefing.bak" "$1"
    fi
  elif [[ ! -e "$1" && -e "$1.pre-briefing.bak" ]]; then
    run mv "$1.pre-briefing.bak" "$1"
  fi
}

# agent_present NAME - is the given agent installed on this machine?
# Project-level delivery is gated on this, so linking a project only
# creates artifacts for agents that can actually read them (a later
# `briefing install` re-links every registered project, so an agent
# installed afterwards gets its links then). Cursor is an IDE without a
# stable CLI name everywhere, so its config directory counts as presence.
agent_present() {
  case "$1" in
    cursor) command -v cursor >/dev/null || command -v cursor-agent >/dev/null \
              || [[ -d "$HOME/.cursor" ]] ;;
    *) command -v "$1" >/dev/null ;;
  esac
}

# Machine-local gitignore block for the artifacts `briefing link` generates.
# Lives in .git/info/exclude, never in the project's committed .gitignore:
# the artifacts are machine-local, so their ignoring is too. Always lists
# every agent's artifacts, so installing an agent later can't leak links
# into a commit before the next re-link refreshes the block.
EXCLUDE_BEGIN='# >>> briefing - generated by briefing link, do not edit >>>'
EXCLUDE_END='# <<< briefing <<<'
EXCLUDE_PATTERNS='.vibe/skills/
.cursor/skills/
.claude/skills/
.cursor/rules/briefing.mdc
HERMES.md
CLAUDE.md'

# project_exclude_file DIR - absolute path of DIR's .git/info/exclude,
# empty when DIR is not a git work tree (nothing to manage then).
project_exclude_file() {
  local f
  git -C "$1" rev-parse --is-inside-work-tree >/dev/null 2>&1 || return 0
  f="$(git -C "$1" rev-parse --git-path info/exclude)"
  [[ "$f" == /* ]] || f="$1/$f"
  printf '%s\n' "$f"
}

# write_exclude_block DIR PATTERNS - idempotently (re)write the briefing
# block in DIR's .git/info/exclude; empty PATTERNS removes the block.
write_exclude_block() {
  local file tmp
  file="$(project_exclude_file "$1")"
  [[ -n "$file" ]] || return 0
  if [[ "${DRY_RUN:-0}" == "1" ]]; then
    if [[ -n "$2" ]]; then
      printf 'would update: %s (briefing block)\n' "$file"
    elif [[ -f "$file" ]] && grep -qxF "$EXCLUDE_BEGIN" "$file"; then
      printf 'would remove: %s (briefing block)\n' "$file"
    fi
    return 0
  fi
  # removing a block that was never written must not create the file
  if [[ -z "$2" && ! -f "$file" ]]; then return 0; fi
  mkdir -p "$(dirname "$file")"
  tmp="$(mktemp)"
  if [[ -f "$file" ]]; then
    awk -v b="$EXCLUDE_BEGIN" -v e="$EXCLUDE_END" \
      '$0==b{skip=1;next} $0==e{skip=0;next} !skip' "$file" > "$tmp"
  fi
  if [[ -n "$2" ]]; then
    [[ -s "$tmp" ]] && echo >> "$tmp"
    printf '%s\n%s\n%s\n' "$EXCLUDE_BEGIN" "$2" "$EXCLUDE_END" >> "$tmp"
  fi
  mv "$tmp" "$file"
}

# resolve_path FILE - follow the symlink chain of FILE itself, portably
# (macOS only gained `readlink -f` in 12.3). Directory components are kept
# logical, matching how $HUB and every symlink target are constructed.
resolve_path() {
  local p="$1" target
  while [[ -L "$p" ]]; do
    target="$(readlink "$p")"
    [[ "$target" == /* ]] || target="$(dirname "$p")/$target"
    p="$target"
  done
  printf '%s\n' "$(cd "$(dirname "$p")" && pwd)/$(basename "$p")"
}

# hub_version - human-readable stamp of the hub's current state (tag, commit,
# dirty marker). Written into generated files so `status` can tell *why* a
# copy diverged instead of just reporting that it did.
hub_version() {
  git -C "$HUB" describe --tags --always --dirty 2>/dev/null || echo unknown
}

# hash_stdin - sha256 of stdin, first field only. Stamped into generated
# files at generation time so `status` can tell a hand-edited copy (body no
# longer matches its own stamp) from a merely outdated one.
hash_stdin() {
  if command -v sha256sum >/dev/null; then
    sha256sum | cut -d' ' -f1
  else
    shasum -a 256 | cut -d' ' -f1
  fi
}

# emit_text FILE - print FILE with a guaranteed terminating newline (awk
# treats an unterminated last line as a full record and print re-adds ORS).
# Generated copies and their sha stamps are built from this normalized form:
# the extraction pipelines in `status` re-terminate the last line anyway, so
# a source file missing its final newline would otherwise diff/hash forever
# as "hand-edited".
emit_text() { awk 1 "$1"; }

# write_file DST - write stdin to DST, honoring dry runs (input is discarded
# but still consumed, so pipelines behave identically in both modes).
write_file() {
  if [[ "${DRY_RUN:-0}" == "1" ]]; then
    printf 'would write: %s\n' "$1"
    cat > /dev/null
  else
    cat > "$1"
  fi
}
